---
- name: Set managerip in global.sls
  yedit:
    src: "{{ securityonion_salt_globalconfig }}"
    key: managerip
    value: "{{ ansible_default_ipv4.address }}"

- name: Set url_base in global.sls
  yedit:
    src: "{{ securityonion_salt_globalconfig }}"
    key: url_base
    value: "{{ ansible_default_ipv4.address }}"
