---
- name: Set managerip in global.sls
  become: true
  yedit:
    src: "{{ securityonion_salt_globalconfig }}"
    key: managerip
    value: "{{ securityonion_management_nic }}"

- name: Set url_base in global.sls
  become: true
  yedit:
    src: "{{ securityonion_salt_globalconfig }}"
    key: url_base
    value: "{{ securityonion_management_nic }}"
