---
- name: Load a variable file based on the OS type
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - default.yaml

- name: Security Onion installation for CentOS iso
  include_tasks: centos.yml
  when: ansible_os_family == 'RedHat'

- name: Security Onion installation for on plain ubuntu via git
  include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Check if global.sls exists
  become: true
  stat:
    path: "{{ securityonion_salt_globalconfig }}"
  register: global_sls

- name: Configure SecurityOnion via global.sls
  include_tasks: configure.yml
  when: global_sls.stat.exists
